var colorsArray = {
    colors:[
        {
            "name":"green",
            "red":"0",
            "green":"255",
            "blue":"0",
        },
        {
            "name":"yellow",
            "red":"255",
            "green":"255",
            "blue":"0"
        },
        {
            name:"red",
            red:"255",
            green:"0",
            blue:"0"
        },
        {
            "name":"blue",
            "red":"0",
            "green":"0",
            "blue":"255",
        },
        {
            "name":"orange",
            "red":"255",
            "green":"100",
            "blue":"0"
        },
    ]
}
